version: '3.6'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    volumes:
      - type: bind
        source: ../Boho-ASM
        target: /app
    ports:
      - "8069:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: admin-pa
      DB_USERNAME: root
      DB_PASSWORD: toor
  db:
    build: postgres/alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: admin-pa
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "6091:80"
    links:
      - "db:pgsql-server"
